title: Sanjeev Kumar Varun
logo: /assets/img/profile-image.jpg
description: Australia India Research Student (AIRS) Fellow || Visiting Scholar@ UTS Sydney, Australia || PhD IIT Roorkee, Uttarakhand || Research -  Neurological Disorder, Brain Connectivity, Epilepsy 
#show_downloads: true
theme: jekyll-theme-minimal
